name: openmrs-playwright-automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 5. Run ESLint check
      - name: Run ESLint
        run: npm run lint

      # 6. Run Playwright tests with Allure
      - name: Run Playwright tests
        run: npm run test:staging

      # 7. Generate Allure report
      - name: Generate Allure report
        run: npm run allure:generate

      # 8. Upload Allure results as artifact
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # 9. Upload Allure HTML report as artifact
      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
